config:
  line-length:
    line_length: 120
    #stern: true
    code_blocks: false

  # these are apparently in conflict with prettier's markdown formatting
  list-marker-space: false
  list-indent: false
  ul-indent: false

  headings: false

  proper-names:
    code_blocks: false
    names:
    - CommonMark
    - JavaScript
    - Markdown
    - markdown-it
    - markdownlint
    - markdownlint-cli2
    - Node.js

fix: true

ignores:
- CHANGELOG.md
- google_internal/LATEST_RELEASE.md
