namespace: "default"
domain: "adsapi.microsoft"
imageRegistry: "privacysandboxdev.azurecr.io"
services:
 - name: bidding-service
   replicas: 3
   image: "/services/bidding_service:eubert-20240828"
   containerPort: 50057
   internalLB: true
 - name: bfe
   replicas: 3
   image: "/services/buyer_frontend_service:eubert-20240828"
   containerPort: 50051
 - name: auction-service
   replicas: 3
   image: "/services/auction_service:eubert-20240828"
   containerPort: 50061
   internalLB: true
 - name: sfe
   replicas: 3
   image: "/services/seller_frontend_service:eubert-20240828"
   containerPort: 50053
env:
  - name: 'ENABLE_ENCRYPTION'
    value: 'true'
  - name: 'PRIVATE_KEY_CACHE_TTL_SECONDS'
    value: '3888000'
  - name: 'KEY_REFRESH_FLOW_RUN_FREQUENCY_SECONDS'
    value: '10800'
  - name: 'TELEMETRY_CONFIG'
    value: 'mode: EXPERIMENT'
  - name: 'TEST_MODE'
    value: 'false'
  - name: 'ENABLE_OTEL_BASED_LOGGING'
    value: 'false'
  - name: 'ENABLE_PROTECTED_APP_SIGNALS'
    value: 'false'
  - name: 'ENABLE_PROTECTED_AUDIENCE'
    value: 'true'
  - name: 'PS_VERBOSITY'
    value: '10'
  - name: 'MAX_ALLOWED_SIZE_DEBUG_URL_BYTES'
    value: '1'
  - name: 'MAX_ALLOWED_SIZE_ALL_DEBUG_URLS_KB'
    value: '1'
  - name: 'BIDDING_PORT'
    value: '50057'
  - name: 'BIDDING_HEALTHCHECK_PORT'
    value: '50551'
  - name: 'ENABLE_BIDDING_SERVICE_BENCHMARK'
    value: 'true'
  - name: 'BUYER_CODE_FETCH_CONFIG'
    value: '{"fetchMode": 0, "biddingJsPath": "","biddingJsUrl": "https://raw.githubusercontent.com/KenGordon/bidding-auction-servers/host-generatebid-js/generateBid.js","protectedAppSignalsBiddingJsUrl": "https://raw.githubusercontent.com/KenGordon/bidding-auction-servers/host-generatebid-js/generateBid.js","biddingWasmHelperUrl": "","protectedAppSignalsBiddingWasmHelperUrl": "","urlFetchPeriodMs": 13000000,"urlFetchTimeoutMs": 120000,"enableBuyerDebugUrlGeneration": true,"enableAdtechCodeLogging": false,"prepareDataForAdsRetrievalJsUrl": "","prepareDataForAdsRetrievalWasmHelperUrl": ""}'
  - name: 'JS_NUM_WORKERS'
    value: '4'
  - name: 'JS_WORKER_QUEUE_LEN'
    value: '100'
  - name: 'BYOS_AD_RETRIEVAL_SERVER'
    value: 'true'
  - name: 'AD_RETRIEVAL_TIMEOUT_MS'
    value: '60000'
  - name: 'BUYER_FRONTEND_PORT'
    value: '50051'
  - name: 'BUYER_FRONTEND_HEALTHCHECK_PORT'
    value: '50552'
  - name: 'BIDDING_SERVER_ADDR'
    value: 'bidding-service.adsapi.microsoft:50057' # change this
  - name: 'BUYER_KV_SERVER_ADDR'
    value: 'https://wonderful-smoke-f7f0a95bd29f428f8933d258d315c801.azurewebsites.net'
  - name: 'GENERATE_BID_TIMEOUT_MS'
    value: '60000'
  - name: 'PROTECTED_APP_SIGNALS_GENERATE_BID_TIMEOUT_MS'
    value: '60000'
  - name: 'BIDDING_SIGNALS_LOAD_TIMEOUT_MS'
    value: '60000'
  - name: 'ENABLE_BUYER_FRONTEND_BENCHMARKING'
    value: 'true'
  - name: 'CREATE_NEW_EVENT_ENGINE'
    value: 'false'
  - name: 'ENABLE_BIDDING_COMPRESSION'
    value: 'true'
  - name: 'AUCTION_PORT'
    value: '50061'
  - name: 'AUCTION_HEALTHCHECK_PORT'
    value: '50553'
  - name: 'ENABLE_AUCTION_SERVICE_BENCHMARK'
    value: 'true'
  - name: 'SELLER_CODE_FETCH_CONFIG'
    value: '{"auctionJsPath": "","auctionJsUrl": "https://pubads.g.doubleclick.net/td/sjs","urlFetchPeriodMs": 13000000,"urlFetchTimeoutMs": 30000,"enableSellerDebugUrlGeneration": false,"enableAdtechCodeLogging": false,"enableReportResultUrlGeneration": true,"enableReportWinUrlGeneration": true,"buyerReportWinJsUrls": {"https://td.doubleclick.net":"https://raw.githubusercontent.com/KenGordon/bidding-auction-servers/host-generatebid-js/generateBid.js"},"protectedAppSignalsBuyerReportWinJsUrls": {"https://td.doubleclick.net":"https://storage.googleapis.com/wasm-explorer/PAS/PASreportWin.js"}}'
  - name: 'ENABLE_REPORT_WIN_INPUT_NOISING'
    value: 'false'
  - name: 'SELLER_FRONTEND_PORT'
    value: '50053'
  - name: 'SELLER_FRONTEND_HEALTHCHECK_PORT'
    value: '50050'
  - name: 'GET_BID_RPC_TIMEOUT_MS'
    value: '60000'
  - name: 'KEY_VALUE_SIGNALS_FETCH_RPC_TIMEOUT_MS'
    value: '60000'
  - name: 'SCORE_ADS_RPC_TIMEOUT_MS'
    value: '60000'
  - name: 'SELLER_ORIGIN_DOMAIN'
    value: 'https://securepubads.g.doubleclick.net'
  - name: 'AUCTION_SERVER_HOST' # change this
    value: 'auction-service.adsapi.microsoft:50061'
  - name: 'KEY_VALUE_SIGNALS_HOST'
    value: 'https://pubads.g.doubleclick.net/td/sts'
  - name: 'BUYER_SERVER_HOSTS'
    value: '{"https://td.doubleclick.net": {"url": "localhost:50051","cloudPlatform": "LOCAL"}}'
  - name: 'ENABLE_SELLER_FRONTEND_BENCHMARKING'
    value: 'true'
  - name: 'SECONDARY_COORDINATOR_PRIVATE_KEY_ENDPOINT'
    value: ''
  - name: 'PRIMARY_COORDINATOR_ACCOUNT_IDENTITY'
    value: ''
  - name: 'SECONDARY_COORDINATOR_ACCOUNT_IDENTITY'
    value: ''
  - name: 'PRIMARY_COORDINATOR_REGION'
    value: ''
  - name: 'SECONDARY_COORDINATOR_REGION'
    value: ''
  - name: 'GCP_PRIMARY_WORKLOAD_IDENTITY_POOL_PROVIDER'
    value: ''
  - name: 'GCP_SECONDARY_WORKLOAD_IDENTITY_POOL_PROVIDER'
    value: ''
  - name: 'GCP_PRIMARY_KEY_SERVICE_CLOUD_FUNCTION_URL'
    value: ''
  - name: 'GCP_SECONDARY_KEY_SERVICE_CLOUD_FUNCTION_URL'
    value: ''
  - name: 'ROMA_TIMEOUT_MS'
    value: ''
  - name: 'COLLECTOR_ENDPOINT'
    value: ''
  - name: 'CONSENTED_DEBUG_TOKEN'
    value: ''
  - name: 'AD_RETRIEVAL_KV_SERVER_ADDR'
    value: ''
  - name: 'BFE_INGRESS_TLS'
    value: ''
  - name: 'BFE_TLS_KEY'
    value: ''
  - name: 'BFE_TLS_CERT'
    value: ''
  - name: 'BIDDING_EGRESS_TLS'
    value: ''
  - name: 'ENABLE_BUYER_COMPRESSION'
    value: ''
  - name: 'ENABLE_AUCTION_COMPRESSION'
    value: ''
  - name: 'SFE_INGRESS_TLS'
    value: ''
  - name: 'SFE_TLS_KEY'
    value: ''
  - name: 'SFE_TLS_CERT'
    value: ''
  - name: 'AUCTION_EGRESS_TLS'
    value: ''
  - name: 'BUYER_EGRESS_TLS'
    value: ''
  - name: 'TEE_KV_SERVER_ADDR'
    value: ''
  - name: 'INFERENCE_MODEL_LOCAL_PATHS'
    value: ''
  - name: 'INFERENCE_MODEL_BUCKET_NAME'
    value: ''
  - name: 'INFERENCE_MODEL_BUCKET_PATHS'
    value: ''
  - name: 'INFERENCE_SIDECAR_BINARY_PATH'
    value: ''
  - name: 'KV_SERVER_EGRESS_TLS'
    value: ''
  - name: 'AD_RETRIEVAL_KV_SERVER_EGRESS_TLS'
    value: ''
  - name: 'TEE_AD_RETRIEVAL_KV_SERVER_ADDR'
    value: ''
  - name: 'AZURE_BA_PARAM_GET_TOKEN_URL'
    value: 'http://169.254.169.254/metadata/identity/oauth2/token'
  - name: 'AZURE_BA_PARAM_KEY_VAULT_URL'
    value: 'https://privacysandboxdevakv.vault.azure.net'
  - name: 'AZURE_BA_METADATA_OPERATOR'
    value: 'testoperator'
  - name: 'AZURE_BA_METADATA_ENVIRONMENT'
    value: 'testenvironment'
  - name: 'PUBLIC_KEY_ENDPOINT'
    value: 'https://eubert-20240829-kms.eastus.azurecontainer.io:8000/app/listpubkeys'
  - name: 'PRIMARY_COORDINATOR_PRIVATE_KEY_ENDPOINT'
    value: 'https://eubert-20240829-kms.eastus.azurecontainer.io:8000/app/key?fmt=tink'
  - name: 'SFE_PUBLIC_KEYS_ENDPOINTS'
    value: '{"AZURE": "https://eubert-20240829-kms.eastus.azurecontainer.io:8000/app/listpubkeys"}'
  - name: 'AZURE_BA_PARAM_KMS_UNWRAP_URL'
    value: 'http://eubert-20240829-kms.eastus.azurecontainer.io:8000/app/unwrapKey?fmt=tink'